{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rbpo.fullname" . }}
  labels:
    {{- include "rbpo.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
