apiVersion: v1
kind: Service
metadata:
  name: {{ include "rbpo.fullname" . }}
  labels:
    {{- include "rbpo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "rbpo.appSelector" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
